### ISSUE TITLE
Login Not Working / Failure

### ISSUE THREAD

**Issue by thulotechnology** [daughterteresa/Automation-Project#1]
Test Case ID: 1

Test Case Name: 

Test Data: 
User name : Admin
Password: password123

Test Step
1. Open URL .......................
2. Click Login Button
3. Enter Username
4. Enter Password
5. Click sign in button

Expected Result: Login Should Work
Actual Result: Login is Not  @Working
![Youtube Thumbnail Income great ideas low investment (14)](https://user-images.githubusercontent.com/62342613/167231217-2589706a-7c9f-4848-b3a7-b87c6f2b0eb5.png)

**Comment by daughterteresa** [comment]
issue is solved
